name: Unit tests

on:
  push:
    branches:
      - "**"

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: on PRs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
